
languageCode = "en-us"
Title = "A Rosebud Rejoicing"
#theme = "ga-hugo-theme"
#theme = "kiss"
theme = "showcase"

#Kiss Configurations
#copyright = "&copy; <a href=\"https://github.com/ribice\">Emir Ribic</a> 2017"
#disqusShortname = "shortname"
googleAnalytics = ""
# Number of posts per page
Paginate = 5
enableRobotsTXT = true

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "A Rosebud Rejoicing" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article




[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

twitter = "@kalikakay"
github = "kalikakay"
email = "kalika_kay@hotmail.com"
linkedin = ""
facebook = ""
instagram = ""
codepen = ""

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = false
### End Kiss Configurations